### ISSUE TITLE
FileNotFoundError: README.md when installing ptv 0.1 with pip

### ISSUE THREAD

**Issue by Lx** [andycasey/ptv#1]
Looks like the `sdist` might be broken, preventing installation & further evaluation:

```
$ pip install ptv==0.1
Collecting ptv==0.1
  Using cached https://files.pythonhosted.org/packages/77/72/221263344a89e3984af4f7dac9c07b0edb9392a17f58b05bbd69f82ea3e2/ptv-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0l/.../T/pip-install-ns5nvohm/ptv/setup.py", line 39, in <module>
        readfile(os.path.join(os.path.dirname(__file__), "README.md"))
      File "/private/var/folders/0l/.../T/pip-install-ns5nvohm/ptv/setup.py", line 19, in readfile
        with open(filename, **readfile_kwargs) as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/0l/.../T/pip-install-ns5nvohm/ptv/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/0l/.../T/pip-install-ns5nvohm/ptv/
```

**Comment by andycasey** [comment]
Yeah: there's not even a `setup.py` currently in the repository because I realised that some functionality existed in v2 of the PTV API, and some in v3, but the same functionality was not available in both. So for what I wanted to do I would need to have v2 credentials, v3 credentials, and a mapper that would use v2/v3 depending on what function was being called.

And v2/v3 were very different from each other.

So instead I decided to drop this project until their API converged. Maybe it has now?

**Comment by Lx** [comment]
I'm not sure, sorry.  My knowledge of the differences between the APIs is very little.

Notwithstanding the plan for future releases, it might be a good idea to just delete [the current release](https://pypi.org/project/ptv/0.1/) off PyPI in the interim?
